# Generated by Django 5.0.6 on 2024-06-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_ai_description_task_creation_date_task_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
